from pathlib import Path
p=Path('leaderboards.js')
s=p.read_text(encoding='utf-8')

def one(old,new,label):
    global s
    c=s.count(old)
    if c!=1: raise SystemExit(f'{label}: expected 1 match, got {c}')
    s=s.replace(old,new,1)

one("function demoRows(view,anchor){if(view==='daily30')return demoDay(anchor);const t=today();let ds=view==='week'?between(anchor,addDays(anchor,6)).filter(d=>d<=t):view==='month'?Array.from({length:dim(anchor.slice(0,7))},(_,i)=>anchor.slice(0,7)+'-'+String(i+1).padStart(2,'0')).filter(d=>d<=t&&d>=START):between(START,t),m=new Map();ds.forEach(d=>demoDay(d).forEach(x=>{const c=m.get(x.id)||{id:x.id,name:x.name,score:0,durationSeconds:0,played:0,isPlayer:false};c.score+=x.score;c.durationSeconds+=x.durationSeconds;c.played++;m.set(x.id,c)}));return[...m.values()]}",
"function demoRows(view,anchor){if(view==='daily30')return demoDay(anchor);const from=view==='week'?weekStart(anchor):view==='month'?monthStart(anchor):START,ds=between(from,anchor),m=new Map();ds.forEach(d=>demoDay(d).forEach(x=>{const c=m.get(x.id)||{id:x.id,name:x.name,score:0,durationSeconds:0,played:0,isPlayer:false};c.score+=x.score;c.durationSeconds+=x.durationSeconds;c.played++;m.set(x.id,c)}));return[...m.values()]}", 'demoRows')

one("function ownVisible(){return window.KvizDaily30?.getLeaderboardVisibility?.()!==false}function localRows(view,anchor){if(!ownVisible())return[];const r=window.KvizDaily30?.getResults?.()||{},name=window.KvizDaily30?.getPublicPlayerName?.()||(lang()==='en'?'Your score':'Tvoj rezultat');if(view==='daily30'){const x=r[anchor];return x?.official?[{id:'local-player',name,score:+x.score||0,durationSeconds:+x.durationSeconds||0,played:1,isPlayer:true}]:[]}const ds=Object.keys(r).filter(d=>r[d]?.official&&(view==='week'?d>=anchor&&d<=addDays(anchor,6):view==='month'?d.startsWith(anchor.slice(0,7)):true));return ds.length?[{id:'local-player',name,score:ds.reduce((s,d)=>s+(+r[d].score||0),0),durationSeconds:ds.reduce((s,d)=>s+(+r[d].durationSeconds||0),0),played:ds.length,isPlayer:true}]:[]}",
"function ownVisible(){return window.KvizDaily30?.getLeaderboardVisibility?.()!==false}function localRows(view,anchor){if(!ownVisible())return[];const r=window.KvizDaily30?.getResults?.()||{},name=window.KvizDaily30?.getPublicPlayerName?.()||(lang()==='en'?'Your score':'Tvoj rezultat');if(view==='daily30'){const x=r[anchor];return x?.official?[{id:'local-player',name,score:+x.score||0,durationSeconds:+x.durationSeconds||0,played:1,isPlayer:true}]:[]}const from=view==='week'?weekStart(anchor):view==='month'?monthStart(anchor):START,ds=Object.keys(r).filter(d=>r[d]?.official&&d>=from&&d<=anchor);return ds.length?[{id:'local-player',name,score:ds.reduce((sum,d)=>sum+(+r[d].score||0),0),durationSeconds:ds.reduce((sum,d)=>sum+(+r[d].durationSeconds||0),0),played:ds.length,isPlayer:true}]:[]}", 'localRows')

one("function remoteRows(view,anchor){const ownKey=window.KvizDaily30?.leaderboardPlayerKey?.(),t=today();let rows=REMOTE.filter(x=>x.quiz_date>=START&&x.quiz_date<=t);if(!ownVisible()&&ownKey)rows=rows.filter(x=>x.player_key!==ownKey);if(view==='daily30')rows=rows.filter(x=>x.quiz_date===anchor);else if(view==='week')rows=rows.filter(x=>x.quiz_date>=anchor&&x.quiz_date<=addDays(anchor,6));else if(view==='month')rows=rows.filter(x=>x.quiz_date.startsWith(anchor.slice(0,7)));const m=new Map();rows.forEach(x=>{const id='real:'+x.player_key,c=m.get(id)||{id,name:x.player_name,score:0,durationSeconds:0,played:0,isPlayer:ownKey===x.player_key,playerKey:x.player_key};c.score+=+x.score||0;c.durationSeconds+=+x.duration_seconds||0;c.played++;c.name=x.player_name||c.name;m.set(id,c)});return[...m.values()]}",
"function remoteRows(view,anchor){const ownKey=window.KvizDaily30?.leaderboardPlayerKey?.();let rows=REMOTE.filter(x=>x.quiz_date>=START&&x.quiz_date<=anchor);if(!ownVisible()&&ownKey)rows=rows.filter(x=>x.player_key!==ownKey);if(view==='daily30')rows=rows.filter(x=>x.quiz_date===anchor);else if(view==='week')rows=rows.filter(x=>x.quiz_date>=weekStart(anchor));else if(view==='month')rows=rows.filter(x=>x.quiz_date>=monthStart(anchor));const m=new Map();rows.forEach(x=>{const id='real:'+x.player_key,c=m.get(id)||{id,name:x.player_name,score:0,durationSeconds:0,played:0,isPlayer:ownKey===x.player_key,playerKey:x.player_key};c.score+=+x.score||0;c.durationSeconds+=+x.duration_seconds||0;c.played++;c.name=x.player_name||c.name;m.set(id,c)});return[...m.values()]}", 'remoteRows')

one("function currentAnchor(v){const t=today();return v==='week'?weekStart(t):v==='month'?monthStart(t):t}function oldest(){return addDays(today(),-(HISTORY-1))}function clamp(a){return a>today()?today():a<oldest()?oldest():a}function period(v,a){const loc=lang()==='en'?'en-GB':'hr-HR',f=k=>new Intl.DateTimeFormat(loc,{timeZone:'UTC',day:'numeric',month:'short',year:'numeric'}).format(parse(k));if(v==='daily30')return window.KvizDaily30?.formatFullDate?.(a)||f(a);if(v==='week')return`${f(a)} – ${f(addDays(a,6))}`;if(v==='month'){const x=new Intl.DateTimeFormat(loc,{timeZone:'UTC',month:'long',year:'numeric'}).format(parse(a));return x[0].toUpperCase()+x.slice(1)}return''}",
"function currentAnchor(v){return today()}function oldest(){return START}function clamp(a){return a>today()?today():a<oldest()?oldest():a}function period(v,a){const loc=lang()==='en'?'en-GB':'hr-HR',f=k=>new Intl.DateTimeFormat(loc,{timeZone:'UTC',day:'numeric',month:'short',year:'numeric'}).format(parse(k));if(v==='daily30')return window.KvizDaily30?.formatFullDate?.(a)||f(a);if(v==='week')return`${f(weekStart(a))} – ${f(a)}`;if(v==='month'){const x=new Intl.DateTimeFormat(loc,{timeZone:'UTC',month:'long',year:'numeric'}).format(parse(a));return`${x[0].toUpperCase()+x.slice(1)} · ${lang()==='en'?'through':'do'} ${f(a)}`}return`${lang()==='en'?'As of':'Stanje na'} ${f(a)}`}", 'period')

old="function renderPreview(){const root=document.getElementById('leaderboard-preview'),list=document.getElementById('leaderboard-preview-list');if(!root||!list)return;if(!previewState.anchor)previewState.anchor=currentAnchor(previewState.view);if(previewState.view==='daily30')previewState.anchor=clamp(previewState.anchor);tabs(root,previewState.view);const pr=document.getElementById('leaderboard-preview-period');if(pr)pr.textContent=previewState.view==='all'?'':period(previewState.view,previewState.anchor);const rows=ranked(previewState.view,previewState.anchor),expanded=root.dataset.expanded==='1',shown=expanded?rows:rows.slice(0,5);list.innerHTML=shown.length?shown.map(x=>row(x,previewState.view)).join(''):`<div class=\"leaderboard-empty\">${lang()==='en'?'No results yet.':'Još nema rezultata.'}</div>`;const own=rows.find(x=>x.isPlayer),ownRoot=document.getElementById('leaderboard-preview-own');if(ownRoot){const show=!expanded&&!!(own&&own.rank>5);ownRoot.classList.toggle('visible',show);ownRoot.innerHTML=show?row(own,previewState.view):''}const link=document.getElementById('leaderboard-more-link');if(link){link.textContent=expanded?(lang()==='en'?'Show less':'Prikaži manje'):(lang()==='en'?'View full leaderboard':'Prikaži cijelu ljestvicu');link.href='#leaderboard-preview';link.onclick=e=>{e.preventDefault();root.dataset.expanded=expanded?'0':'1';renderPreview();if(!expanded)setTimeout(()=>root.scrollIntoView({behavior:'smooth',block:'start'}),0)}}}"
new="function ensurePreviewDateNav(){const label=document.getElementById('leaderboard-preview-period');if(!label)return;let wrap=document.getElementById('leaderboard-preview-date-nav');if(wrap)return;wrap=document.createElement('div');wrap.id='leaderboard-preview-date-nav';wrap.className='leaderboard-full-period';label.parentNode.insertBefore(wrap,label);const prev=document.createElement('button');prev.type='button';prev.className='leaderboard-period-nav';prev.id='leaderboard-preview-prev';prev.textContent='‹';const next=document.createElement('button');next.type='button';next.className='leaderboard-period-nav';next.id='leaderboard-preview-next';next.textContent='›';wrap.append(prev,label,next);prev.addEventListener('click',()=>shiftPreview(-1));next.addEventListener('click',()=>shiftPreview(1))}function shiftPreview(dir){previewState.anchor=clamp(addDays(previewState.anchor||today(),dir));const root=document.getElementById('leaderboard-preview');if(root)root.dataset.expanded='0';pageState.anchor=previewState.anchor;renderPreview();if(document.getElementById('leaderboard-page')?.classList.contains('open'))renderPage()}function renderPreview(){const root=document.getElementById('leaderboard-preview'),list=document.getElementById('leaderboard-preview-list');if(!root||!list)return;if(!previewState.anchor)previewState.anchor=today();previewState.anchor=clamp(previewState.anchor);tabs(root,previewState.view);ensurePreviewDateNav();const pr=document.getElementById('leaderboard-preview-period');if(pr)pr.textContent=period(previewState.view,previewState.anchor);const pp=document.getElementById('leaderboard-preview-prev'),pn=document.getElementById('leaderboard-preview-next');if(pp){pp.disabled=previewState.anchor<=oldest();pp.setAttribute('aria-label',lang()==='en'?'Previous day':'Prethodni dan')}if(pn){pn.disabled=previewState.anchor>=today();pn.setAttribute('aria-label',lang()==='en'?'Next day':'Sljedeći dan')}const rows=ranked(previewState.view,previewState.anchor),expanded=root.dataset.expanded==='1',shown=expanded?rows:rows.slice(0,5);list.innerHTML=shown.length?shown.map(x=>row(x,previewState.view)).join(''):`<div class=\"leaderboard-empty\">${lang()==='en'?'No results yet.':'Još nema rezultata.'}</div>`;const own=rows.find(x=>x.isPlayer),ownRoot=document.getElementById('leaderboard-preview-own');if(ownRoot){const show=!expanded&&!!(own&&own.rank>5);ownRoot.classList.toggle('visible',show);ownRoot.innerHTML=show?row(own,previewState.view):''}const link=document.getElementById('leaderboard-more-link');if(link){link.textContent=expanded?(lang()==='en'?'Show less':'Prikaži manje'):(lang()==='en'?'View full leaderboard':'Prikaži cijelu ljestvicu');link.href='#leaderboard-preview';link.onclick=e=>{e.preventDefault();root.dataset.expanded=expanded?'0':'1';renderPreview();if(!expanded)setTimeout(()=>root.scrollIntoView({behavior:'smooth',block:'start'}),0)}}}"
one(old,new,'renderPreview')

one("function renderPage(){const root=document.getElementById('leaderboard-page'),list=document.getElementById('leaderboard-full-list');if(!root||!list)return;if(!pageState.anchor)pageState.anchor=currentAnchor(pageState.view);if(pageState.view==='daily30')pageState.anchor=clamp(pageState.anchor);tabs(root,pageState.view);document.getElementById('leaderboard-full-period')?.classList.toggle('is-all-time',pageState.view==='all');const lab=document.getElementById('leaderboard-full-period-label');if(lab)lab.textContent=period(pageState.view,pageState.anchor);const rs=ranked(pageState.view,pageState.anchor);list.innerHTML=rs.length?rs.map(x=>row(x,pageState.view)).join(''):`<div class=\"leaderboard-empty\">${lang()==='en'?'No results yet.':'Još nema rezultata.'}</div>`;const p=document.getElementById('leaderboard-period-prev'),n=document.getElementById('leaderboard-period-next');if(p)p.disabled=pageState.view==='all'||(pageState.view==='daily30'&&pageState.anchor<=oldest());if(n)n.disabled=pageState.view==='all'||pageState.anchor>=currentAnchor(pageState.view)}function shift(dir){if(pageState.view==='all')return;let x=pageState.anchor;if(pageState.view==='daily30')x=clamp(addDays(x,dir));if(pageState.view==='week')x=addDays(x,dir*7);if(pageState.view==='month')x=addMonths(x,dir);if(dir>0&&x>currentAnchor(pageState.view))x=currentAnchor(pageState.view);pageState.anchor=x;renderPage()}",
"function renderPage(){const root=document.getElementById('leaderboard-page'),list=document.getElementById('leaderboard-full-list');if(!root||!list)return;if(!pageState.anchor)pageState.anchor=previewState.anchor||today();pageState.anchor=clamp(pageState.anchor);tabs(root,pageState.view);document.getElementById('leaderboard-full-period')?.classList.remove('is-all-time');const lab=document.getElementById('leaderboard-full-period-label');if(lab)lab.textContent=period(pageState.view,pageState.anchor);const rs=ranked(pageState.view,pageState.anchor);list.innerHTML=rs.length?rs.map(x=>row(x,pageState.view)).join(''):`<div class=\"leaderboard-empty\">${lang()==='en'?'No results yet.':'Još nema rezultata.'}</div>`;const p=document.getElementById('leaderboard-period-prev'),n=document.getElementById('leaderboard-period-next');if(p){p.disabled=pageState.anchor<=oldest();p.setAttribute('aria-label',lang()==='en'?'Previous day':'Prethodni dan')}if(n){n.disabled=pageState.anchor>=today();n.setAttribute('aria-label',lang()==='en'?'Next day':'Sljedeći dan')}}function shift(dir){pageState.anchor=clamp(addDays(pageState.anchor||today(),dir));previewState.anchor=pageState.anchor;renderPage();renderPreview()}", 'renderPage')

one("pageState.view=b.dataset.leaderboardView;pageState.anchor=currentAnchor(pageState.view);renderPage()", "pageState.view=b.dataset.leaderboardView;pageState.anchor=clamp(pageState.anchor||previewState.anchor||today());renderPage()", 'full tab preserve date')
one("previewState.view=b.dataset.leaderboardView;previewState.anchor=currentAnchor(previewState.view);root.dataset.expanded='0';", "previewState.view=b.dataset.leaderboardView;previewState.anchor=clamp(previewState.anchor||today());root.dataset.expanded='0';", 'preview tab preserve date')

p.write_text(s,encoding='utf-8')
