from pathlib import Path
p=Path('leaderboards.js')
s=p.read_text(encoding='utf-8')

def one(old,new,label):
    global s
    c=s.count(old)
    if c!=1:
        raise SystemExit(f'{label}: expected 1 match, got {c}')
    s=s.replace(old,new,1)

one("const previewState={view:'daily30',anchor:null},pageState={view:'daily30',anchor:null},HISTORY=7,START='2026-08-28';", "const makeAnchors=()=>({daily30:null,week:null,month:null,all:null});const previewState={view:'daily30',anchors:makeAnchors()},pageState={view:'daily30',anchors:makeAnchors()},HISTORY=7,START='2026-08-28';", 'state')

one("function currentAnchor(v){return today()}function oldest(){return START}function clamp(a){return a>today()?today():a<oldest()?oldest():a}function periodEnd(v,a){if(v==='week')return addDays(weekStart(a),6);if(v==='month'){const mk=monthStart(a);return mk.slice(0,7)+'-'+String(dim(mk.slice(0,7))).padStart(2,'0')}return a}", "function currentAnchor(v){return today()}function oldest(){return START}function clamp(a){return a>today()?today():a<oldest()?oldest():a}function getAnchor(state,v){if(v==='all')return today();return clamp(state.anchors[v]||today())}function setAnchor(state,v,a){if(v!=='all')state.anchors[v]=clamp(a)}function periodEnd(v,a){if(v==='week')return addDays(weekStart(a),6);if(v==='month'){const mk=monthStart(a);return mk.slice(0,7)+'-'+String(dim(mk.slice(0,7))).padStart(2,'0')}return a}function periodStart(v,a){return v==='week'?weekStart(a):v==='month'?monthStart(a):a}function hasPreviousCompletePeriod(v,a){if(v==='week'){const prevStart=addDays(weekStart(a),-7),prevEnd=addDays(prevStart,6);return prevStart>=START&&prevEnd<today()}if(v==='month'){const prevStart=addMonths(monthStart(a),-1),prevEnd=periodEnd('month',prevStart);return prevStart>=START&&prevEnd<today()}return a>START}", 'helpers')

one("function demoRows(view,anchor){if(view==='daily30')return demoDay(anchor);const from=view==='week'?weekStart(anchor):view==='month'?monthStart(anchor):START,ds=between(from,anchor),m=new Map();", "function demoRows(view,anchor){if(view==='daily30')return demoDay(anchor);const from=view==='week'?weekStart(anchor):view==='month'?monthStart(anchor):START,to=view==='week'||view==='month'?Math.min?anchor:anchor:anchor,ds=between(from,anchor),m=new Map();", 'demo placeholder')
# repair placeholder cleanly; keep current partial period through anchor for active week/month
s=s.replace("const from=view==='week'?weekStart(anchor):view==='month'?monthStart(anchor):START,to=view==='week'||view==='month'?Math.min?anchor:anchor:anchor,ds=between(from,anchor),m=new Map();", "const from=view==='week'?weekStart(anchor):view==='month'?monthStart(anchor):START,ds=between(from,anchor),m=new Map();",1)

old="function shiftPreview(dir){const a=previewState.anchor||today();previewState.anchor=clamp(previewState.view==='week'?addDays(weekStart(a),dir*7):previewState.view==='month'?addMonths(monthStart(a),dir):addDays(a,dir));const root=document.getElementById('leaderboard-preview');if(root)root.dataset.expanded='0';pageState.anchor=previewState.anchor;renderPreview();if(document.getElementById('leaderboard-page')?.classList.contains('open'))renderPage()}"
new="function shiftPreview(dir){const v=previewState.view;if(v==='all')return;const a=getAnchor(previewState,v);if(dir<0&&!hasPreviousCompletePeriod(v,a))return;const next=v==='week'?addDays(weekStart(a),dir*7):v==='month'?addMonths(monthStart(a),dir):addDays(a,dir);setAnchor(previewState,v,next);const root=document.getElementById('leaderboard-preview');if(root)root.dataset.expanded='0';renderPreview();if(document.getElementById('leaderboard-page')?.classList.contains('open'))renderPage()}"
one(old,new,'shiftPreview')

old="function renderPreview(){const root=document.getElementById('leaderboard-preview'),list=document.getElementById('leaderboard-preview-list');if(!root||!list)return;if(!previewState.anchor)previewState.anchor=today();previewState.anchor=clamp(previewState.anchor);tabs(root,previewState.view);ensurePreviewDateNav();const pr=document.getElementById('leaderboard-preview-period');if(pr)pr.textContent=period(previewState.view,previewState.anchor);const pp=document.getElementById('leaderboard-preview-prev'),pn=document.getElementById('leaderboard-preview-next');if(pp){pp.disabled=previewState.anchor<=oldest();pp.setAttribute('aria-label',lang()==='en'?'Previous day':'Prethodni dan')}if(pn){pn.disabled=previewState.anchor>=today();pn.setAttribute('aria-label',lang()==='en'?'Next day':'Sljedeći dan')}const rows=ranked(previewState.view,previewState.anchor),expanded=root.dataset.expanded==='1',shown=expanded?rows:rows.slice(0,5);"
new="function renderPreview(){const root=document.getElementById('leaderboard-preview'),list=document.getElementById('leaderboard-preview-list');if(!root||!list)return;const v=previewState.view,a=getAnchor(previewState,v);tabs(root,v);ensurePreviewDateNav();const pr=document.getElementById('leaderboard-preview-period');if(pr)pr.textContent=period(v,a);const pp=document.getElementById('leaderboard-preview-prev'),pn=document.getElementById('leaderboard-preview-next');if(pp){pp.disabled=v==='all'||!hasPreviousCompletePeriod(v,a);pp.setAttribute('aria-label',v==='week'?(lang()==='en'?'Previous week':'Prethodni tjedan'):v==='month'?(lang()==='en'?'Previous month':'Prethodni mjesec'):(lang()==='en'?'Previous day':'Prethodni dan'))}if(pn){pn.disabled=v==='all'||periodEnd(v,a)>=today();pn.setAttribute('aria-label',v==='week'?(lang()==='en'?'Next week':'Sljedeći tjedan'):v==='month'?(lang()==='en'?'Next month':'Sljedeći mjesec'):(lang()==='en'?'Next day':'Sljedeći dan'))}const rows=ranked(v,a),expanded=root.dataset.expanded==='1',shown=expanded?rows:rows.slice(0,5);"
one(old,new,'renderPreview start')
s=s.replace("row(x,previewState.view)","row(x,v)")

old="function renderPage(){const root=document.getElementById('leaderboard-page'),list=document.getElementById('leaderboard-full-list');if(!root||!list)return;if(!pageState.anchor)pageState.anchor=previewState.anchor||today();pageState.anchor=clamp(pageState.anchor);tabs(root,pageState.view);document.getElementById('leaderboard-full-period')?.classList.remove('is-all-time');const lab=document.getElementById('leaderboard-full-period-label');if(lab)lab.textContent=period(pageState.view,pageState.anchor);const rs=ranked(pageState.view,pageState.anchor);list.innerHTML=rs.length?rs.map(x=>row(x,pageState.view)).join(''):`<div class=\"leaderboard-empty\">${lang()==='en'?'No results yet.':'Još nema rezultata.'}</div>`;const p=document.getElementById('leaderboard-period-prev'),n=document.getElementById('leaderboard-period-next');if(p){p.disabled=pageState.anchor<=oldest();p.setAttribute('aria-label',lang()==='en'?'Previous day':'Prethodni dan')}if(n){n.disabled=pageState.anchor>=today();n.setAttribute('aria-label',lang()==='en'?'Next day':'Sljedeći dan')}}function shift(dir){const a=pageState.anchor||today();pageState.anchor=clamp(pageState.view==='week'?addDays(weekStart(a),dir*7):pageState.view==='month'?addMonths(monthStart(a),dir):addDays(a,dir));previewState.anchor=pageState.anchor;renderPage();renderPreview()}"
new="function renderPage(){const root=document.getElementById('leaderboard-page'),list=document.getElementById('leaderboard-full-list');if(!root||!list)return;const v=pageState.view,a=getAnchor(pageState,v);tabs(root,v);document.getElementById('leaderboard-full-period')?.classList.remove('is-all-time');const lab=document.getElementById('leaderboard-full-period-label');if(lab)lab.textContent=period(v,a);const rs=ranked(v,a);list.innerHTML=rs.length?rs.map(x=>row(x,v)).join(''):`<div class=\"leaderboard-empty\">${lang()==='en'?'No results yet.':'Još nema rezultata.'}</div>`;const p=document.getElementById('leaderboard-period-prev'),n=document.getElementById('leaderboard-period-next');if(p){p.disabled=v==='all'||!hasPreviousCompletePeriod(v,a);p.setAttribute('aria-label',v==='week'?(lang()==='en'?'Previous week':'Prethodni tjedan'):v==='month'?(lang()==='en'?'Previous month':'Prethodni mjesec'):(lang()==='en'?'Previous day':'Prethodni dan'))}if(n){n.disabled=v==='all'||periodEnd(v,a)>=today();n.setAttribute('aria-label',v==='week'?(lang()==='en'?'Next week':'Sljedeći tjedan'):v==='month'?(lang()==='en'?'Next month':'Sljedeći mjesec'):(lang()==='en'?'Next day':'Sljedeći dan'))}}function shift(dir){const v=pageState.view;if(v==='all')return;const a=getAnchor(pageState,v);if(dir<0&&!hasPreviousCompletePeriod(v,a))return;const next=v==='week'?addDays(weekStart(a),dir*7):v==='month'?addMonths(monthStart(a),dir):addDays(a,dir);setAnchor(pageState,v,next);renderPage()}"
one(old,new,'renderPage+shift')

old="el.querySelectorAll('[data-leaderboard-view]').forEach(b=>b.addEventListener('click',()=>{pageState.view=b.dataset.leaderboardView;pageState.anchor=clamp(pageState.anchor||previewState.anchor||today());renderPage()}));"
new="el.querySelectorAll('[data-leaderboard-view]').forEach(b=>b.addEventListener('click',()=>{pageState.view=b.dataset.leaderboardView;if(pageState.view!=='all'&&!pageState.anchors[pageState.view])pageState.anchors[pageState.view]=getAnchor(previewState,pageState.view);renderPage()}));"
one(old,new,'page tab')

old="previewState.view='daily30';previewState.anchor=currentAnchor('daily30');"
new="previewState.view='daily30';previewState.anchors.daily30=currentAnchor('daily30');previewState.anchors.week=currentAnchor('week');previewState.anchors.month=currentAnchor('month');"
one(old,new,'init')

old="previewState.view=b.dataset.leaderboardView;previewState.anchor=clamp(previewState.anchor||today());root.dataset.expanded='0';"
new="previewState.view=b.dataset.leaderboardView;if(previewState.view!=='all'&&!previewState.anchors[previewState.view])previewState.anchors[previewState.view]=today();root.dataset.expanded='0';"
one(old,new,'preview tab')

p.write_text(s,encoding='utf-8')
