from pathlib import Path

hp=Path('online-kviz.html')
s=hp.read_text(encoding='utf-8')
old='''    <div class="leaderboard-section-tabs" aria-label="Vrsta ljestvice">\n      <button class="leaderboard-section-tab leaderboard-section-tab--soon" type="button" disabled aria-disabled="true"><span>Multiplayer</span><small>Uskoro</small></button>\n      <button class="leaderboard-section-tab active" type="button" aria-pressed="true">Dnevnih 30</button>\n    </div>'''
new='''    <div class="leaderboard-section-tabs" aria-label="Vrsta ljestvice">\n      <button class="leaderboard-section-tab active" type="button" aria-pressed="true">Dnevnih 30</button>\n      <button class="leaderboard-section-tab leaderboard-section-tab--soon" type="button" disabled aria-disabled="true"><span>Multiplayer</span><small>Uskoro</small></button>\n    </div>'''
if old not in s:
    raise SystemExit('section block not found')
hp.write_text(s.replace(old,new,1),encoding='utf-8')

jp=Path('leaderboards.js')
j=jp.read_text(encoding='utf-8')
old_css='.leaderboard-section-tabs{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.34rem;margin:.15rem 0 .55rem;padding:.3rem;border-radius:14px;border:1px solid rgba(148,163,184,.18);background:rgba(0,0,0,.2)}.leaderboard-section-tab{min-width:0;min-height:42px;border:1px solid transparent;border-radius:11px;background:transparent;color:var(--leader-muted);padding:.42rem .45rem;font-size:.72rem;font-weight:950;display:flex;align-items:center;justify-content:center;gap:.38rem}.leaderboard-section-tab.active{background:linear-gradient(135deg,rgba(47,128,255,.98),rgba(28,113,238,.98));border-color:rgba(115,173,255,.48);color:#fff;box-shadow:0 7px 18px rgba(47,128,255,.16)}.leaderboard-section-tab--soon{opacity:.58;cursor:not-allowed}.leaderboard-section-tab--soon small{font-size:.52rem;font-weight:950;text-transform:uppercase;letter-spacing:.04em;padding:.13rem .3rem;border-radius:999px;border:1px solid rgba(148,163,184,.28);background:rgba(255,255,255,.055);color:#cbd5e1}.leaderboard-tabs{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.28rem;padding:.28rem;border-radius:13px;border:1px solid rgba(148,163,184,.16);background:rgba(0,0,0,.16)}.leaderboard-tab{min-width:0;min-height:35px;border:0;border-radius:10px;background:transparent;color:var(--leader-muted);padding:.36rem .2rem;font-size:.61rem;font-weight:900;line-height:1.12;cursor:pointer}'
new_css='.leaderboard-section-tabs{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.42rem;margin:.1rem 0 .48rem}.leaderboard-section-tab{min-width:0;min-height:32px;border:1px solid var(--leader-border);border-radius:999px;background:rgba(255,255,255,.055);color:var(--leader-muted);padding:.3rem .65rem;font-size:.68rem;font-weight:900;display:flex;align-items:center;justify-content:center;gap:.34rem}.leaderboard-section-tab.active{background:var(--leader-blue);border-color:var(--leader-blue);color:#fff;box-shadow:0 0 14px rgba(47,128,255,.22)}.leaderboard-section-tab--soon{opacity:.55;cursor:default}.leaderboard-section-tab--soon small{font-size:.48rem;font-weight:900;text-transform:uppercase;letter-spacing:.03em;padding:.08rem .24rem;border-radius:999px;border:1px solid rgba(148,163,184,.24);background:rgba(255,255,255,.045);color:#cbd5e1}.leaderboard-tabs{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.2rem;padding:.18rem;border-radius:999px;border:1px solid rgba(148,163,184,.16);background:rgba(0,0,0,.12)}.leaderboard-tab{min-width:0;min-height:24px;border:0;border-radius:999px;background:transparent;color:var(--leader-muted);padding:.16rem .12rem;font-size:.56rem;font-weight:900;line-height:1.05;cursor:pointer}'
if old_css not in j:
    raise SystemExit('old leaderboard visual css not found')
jp.write_text(j.replace(old_css,new_css,1),encoding='utf-8')
