from pathlib import Path

# daily30.js
p=Path('daily30.js')
s=p.read_text(encoding='utf-8')
old='''  function complete(score,total){stopStopwatch();const dateKey=getActiveDate(),today=zonedDateKey(),durationSeconds=Math.max(1,Math.round(elapsedMs()/1000)),results=loadResults(),previous=results[dateKey]||null,official=dateKey===today&&!previous?.official,candidate={date:dateKey,score:Math.max(0,Number(score)||0),total:Math.max(0,Number(total)||30),durationSeconds,completedAt:new Date().toISOString(),official,attempts:Math.max(0,Number(previous?.attempts)||0)+1};if(previous?.official)results[dateKey]={...previous,attempts:candidate.attempts,lastPractice:candidate};else{const previousIsBetter=previous&&(Number(previous.score)>candidate.score||(Number(previous.score)===candidate.score&&Number(previous.durationSeconds)<=candidate.durationSeconds));results[dateKey]=previousIsBetter?{...previous,attempts:candidate.attempts,lastPractice:candidate}:candidate;}saveResults(results);renderCalendar();updateSelectionNote();showNameCardIfNeeded();window.KvizLeaderboards?.refreshAll?.();return results[dateKey];}
'''
new='''  const VISIBILITY_KEY="kviztogo_daily30_leaderboard_visible_v1";
  function getLeaderboardVisibility(){try{return localStorage.getItem(VISIBILITY_KEY)!=="0";}catch{return true;}}
  function setLeaderboardVisibilityLocal(value){try{localStorage.setItem(VISIBILITY_KEY,value?"1":"0");}catch(_){}return Boolean(value);}
  function leaderboardPlayerKey(){const context=getPlayerContext();if(context&&!context.isGuest&&context.userId)return `user:${context.userId}`;if(context?.isGuest&&context.guestId)return `guest:${context.guestId}`;try{if(typeof playerIdentity!=="undefined"&&playerIdentity&&!playerIdentity.isGuest&&playerIdentity.userId)return `user:${playerIdentity.userId}`;if(typeof getOrCreateGuestIdentity==="function"){const g=getOrCreateGuestIdentity();if(g?.id)return `guest:${g.id}`;}}catch(_){}return null;}
  async function publishOfficialResult(result=getResult(zonedDateKey())){if(!result?.official)return false;let client=null;try{client=typeof supabaseClient!=="undefined"?supabaseClient:null;}catch(_){client=null;}if(!client)return false;const context=getPlayerContext(),playerKey=leaderboardPlayerKey();if(!playerKey)return false;let playerName=getPublicPlayerName();if(context?.isGuest){const custom=getCustomGuestName();if(!custom)return false;playerName=custom;}const userId=context&&!context.isGuest?context.userId:null;try{const claim=await client.rpc("daily30_claim_name",{p_player_key:playerKey,p_user_id:userId,p_player_name:playerName});if(claim.error||claim.data!==true)return false;await client.rpc("daily30_set_visibility",{p_player_key:playerKey,p_visible:getLeaderboardVisibility()});const saved=await client.rpc("daily30_save_result",{p_player_key:playerKey,p_user_id:userId,p_player_name:playerName,p_quiz_date:result.date,p_score:Math.max(0,Number(result.score)||0),p_duration_seconds:Math.max(0,Number(result.durationSeconds)||0)});if(saved.error||saved.data!==true)return false;window.KvizLeaderboards?.reloadRemote?.();return true;}catch(error){console.warn("Dnevnih 30 rezultat nije objavljen na ljestvici:",error);return false;}}
  async function setLeaderboardVisibility(value){const visible=setLeaderboardVisibilityLocal(value),playerKey=leaderboardPlayerKey();let client=null;try{client=typeof supabaseClient!=="undefined"?supabaseClient:null;}catch(_){client=null;}if(client&&playerKey){try{await client.rpc("daily30_set_visibility",{p_player_key:playerKey,p_visible:visible});}catch(error){console.warn("Vidljivost ljestvice nije spremljena:",error);}}window.KvizLeaderboards?.reloadRemote?.();window.KvizLeaderboards?.refreshAll?.();return visible;}
  function complete(score,total){stopStopwatch();const dateKey=getActiveDate(),today=zonedDateKey(),durationSeconds=Math.max(1,Math.round(elapsedMs()/1000)),results=loadResults(),previous=results[dateKey]||null,official=dateKey===today&&!previous?.official,candidate={date:dateKey,score:Math.max(0,Number(score)||0),total:Math.max(0,Number(total)||30),durationSeconds,completedAt:new Date().toISOString(),official,attempts:Math.max(0,Number(previous?.attempts)||0)+1};if(previous?.official)results[dateKey]={...previous,attempts:candidate.attempts,lastPractice:candidate};else{const previousIsBetter=previous&&(Number(previous.score)>candidate.score||(Number(previous.score)===candidate.score&&Number(previous.durationSeconds)<=candidate.durationSeconds));results[dateKey]=previousIsBetter?{...previous,attempts:candidate.attempts,lastPractice:candidate}:candidate;}saveResults(results);renderCalendar();updateSelectionNote();showNameCardIfNeeded();if(results[dateKey]?.official)void publishOfficialResult(results[dateKey]);window.KvizLeaderboards?.refreshAll?.();return results[dateKey];}
'''
if old not in s: raise SystemExit('daily30 complete target not found')
s=s.replace(old,new,1)
old='''  window.KvizDaily30={initOnline,onModeSelected,onModeLeft,afterLanguageChange,prepareSelectedRound,getActiveQuestions,getActiveDate,getSelectedDate,getResult,getResults:loadResults,getPublicPlayerName,setPlayerContext,formatDuration,formatFullDate,zonedDateKey,resetStopwatch,startStopwatch,stopStopwatch,renderStopwatch,elapsedSeconds:()=>Math.max(0,Math.round(elapsedMs()/1000)),complete,showNameCardIfNeeded,refreshCalendar:renderCalendar};
'''
new='''  window.KvizDaily30={initOnline,onModeSelected,onModeLeft,afterLanguageChange,prepareSelectedRound,getActiveQuestions,getActiveDate,getSelectedDate,getResult,getResults:loadResults,getPublicPlayerName,getPlayerContext,setPlayerContext,leaderboardPlayerKey,getLeaderboardVisibility,setLeaderboardVisibility,publishOfficialResult,formatDuration,formatFullDate,zonedDateKey,resetStopwatch,startStopwatch,stopStopwatch,renderStopwatch,elapsedSeconds:()=>Math.max(0,Math.round(elapsedMs()/1000)),complete,showNameCardIfNeeded,refreshCalendar:renderCalendar};
'''
if old not in s: raise SystemExit('daily30 export target not found')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')

# online-kviz.html: republish after guest name save
p=Path('online-kviz.html')
s=p.read_text(encoding='utf-8')
old='''    playerIdentity.name = name;
    return true;
'''
new='''    playerIdentity.name = name;
    try { window.KvizDaily30?.setPlayerContext?.(playerIdentity); void window.KvizDaily30?.publishOfficialResult?.(); } catch (_) {}
    return true;
'''
if old not in s: raise SystemExit('guest leaderboard name target not found')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')

# leaderboards.js
p=Path('leaderboards.js')
s=p.read_text(encoding='utf-8')
old=""".leaderboard-own-position{display:none;margin-top:.42rem}.leaderboard-own-position.visible{display:block}.leaderboard-more-link"""
new=""".leaderboard-own-position{display:none;margin-top:.42rem}.leaderboard-own-position.visible{display:block}.leaderboard-visibility{display:flex;align-items:center;justify-content:space-between;gap:.65rem;margin:.42rem 0 .5rem;padding:.4rem .55rem;border:1px solid rgba(148,163,184,.18);border-radius:13px;background:rgba(255,255,255,.035)}.leaderboard-visibility-copy{min-width:0}.leaderboard-visibility-title{color:#fff;font-size:.68rem;font-weight:900}.leaderboard-visibility-note{margin-top:.08rem;color:var(--leader-muted);font-size:.54rem;line-height:1.25}.leaderboard-switch{position:relative;flex:0 0 auto;width:42px;height:24px}.leaderboard-switch input{position:absolute;opacity:0;pointer-events:none}.leaderboard-switch-track{position:absolute;inset:0;border-radius:999px;border:1px solid rgba(148,163,184,.35);background:rgba(148,163,184,.2);cursor:pointer;transition:.18s}.leaderboard-switch-track:after{content:\"\";position:absolute;top:3px;left:3px;width:16px;height:16px;border-radius:50%;background:#fff;transition:.18s}.leaderboard-switch input:checked+.leaderboard-switch-track{background:rgba(34,197,94,.55);border-color:rgba(34,197,94,.8)}.leaderboard-switch input:checked+.leaderboard-switch-track:after{transform:translateX(18px)}.leaderboard-more-link"""
if old not in s: raise SystemExit('leaderboard css target not found')
s=s.replace(old,new,1)
old="""const previewState={view:'daily30',anchor:null},pageState={view:'daily30',anchor:null},HISTORY=7,START='2026-07-01';"""
new="""const previewState={view:'daily30',anchor:null},pageState={view:'daily30',anchor:null},HISTORY=7,START='2026-07-01';let REMOTE=[];let remoteBusy=false;"""
s=s.replace(old,new,1)
old="""function localRows(view,anchor){const r=window.KvizDaily30?.getResults?.()||{},name=window.KvizDaily30?.getPublicPlayerName?.()||(lang()==='en'?'Your score':'Tvoj rezultat');if(view==='daily30'){const x=r[anchor];return x?.official?[{id:'local-player',name,score:+x.score||0,durationSeconds:+x.durationSeconds||0,played:1,isPlayer:true}]:[]}const ds=Object.keys(r).filter(d=>r[d]?.official&&(view==='week'?d>=anchor&&d<=addDays(anchor,6):view==='month'?d.startsWith(anchor.slice(0,7)):true));return ds.length?[{id:'local-player',name,score:ds.reduce((s,d)=>s+(+r[d].score||0),0),durationSeconds:ds.reduce((s,d)=>s+(+r[d].durationSeconds||0),0),played:ds.length,isPlayer:true}]:[]}
function ranked(view,anchor){return[...demoRows(view,anchor),...localRows(view,anchor)].sort((a,b)=>b.score-a.score||a.durationSeconds-b.durationSeconds||a.name.localeCompare(b.name,'hr')).map((x,i)=>({...x,rank:i+1}))}"""
new="""function ownVisible(){return window.KvizDaily30?.getLeaderboardVisibility?.()!==false}function localRows(view,anchor){if(!ownVisible())return[];const r=window.KvizDaily30?.getResults?.()||{},name=window.KvizDaily30?.getPublicPlayerName?.()||(lang()==='en'?'Your score':'Tvoj rezultat');if(view==='daily30'){const x=r[anchor];return x?.official?[{id:'local-player',name,score:+x.score||0,durationSeconds:+x.durationSeconds||0,played:1,isPlayer:true}]:[]}const ds=Object.keys(r).filter(d=>r[d]?.official&&(view==='week'?d>=anchor&&d<=addDays(anchor,6):view==='month'?d.startsWith(anchor.slice(0,7)):true));return ds.length?[{id:'local-player',name,score:ds.reduce((s,d)=>s+(+r[d].score||0),0),durationSeconds:ds.reduce((s,d)=>s+(+r[d].durationSeconds||0),0),played:ds.length,isPlayer:true}]:[]}
function remoteRows(view,anchor){const ownKey=window.KvizDaily30?.leaderboardPlayerKey?.(),t=today();let rows=REMOTE.filter(x=>x.quiz_date>=START&&x.quiz_date<=t);if(view==='daily30')rows=rows.filter(x=>x.quiz_date===anchor);else if(view==='week')rows=rows.filter(x=>x.quiz_date>=anchor&&x.quiz_date<=addDays(anchor,6));else if(view==='month')rows=rows.filter(x=>x.quiz_date.startsWith(anchor.slice(0,7)));const m=new Map();rows.forEach(x=>{const id='real:'+x.player_key,c=m.get(id)||{id,name:x.player_name,score:0,durationSeconds:0,played:0,isPlayer:ownKey===x.player_key,playerKey:x.player_key};c.score+=+x.score||0;c.durationSeconds+=+x.duration_seconds||0;c.played++;c.name=x.player_name||c.name;m.set(id,c)});return[...m.values()]}
function ranked(view,anchor){const rr=remoteRows(view,anchor),hasOwn=rr.some(x=>x.isPlayer),local=hasOwn?[]:localRows(view,anchor);return[...demoRows(view,anchor),...rr,...local].sort((a,b)=>b.score-a.score||a.durationSeconds-b.durationSeconds||a.name.localeCompare(b.name,'hr')).map((x,i)=>({...x,rank:i+1}))}"""
if old not in s: raise SystemExit('leaderboard rows target not found')
s=s.replace(old,new,1)
old="""function injectFull(){if(document.getElementById('leaderboard-page'))return;"""
new="""async function reloadRemote(){if(remoteBusy)return;let client=null;try{client=typeof supabaseClient!=='undefined'?supabaseClient:null}catch(_){client=null}if(!client)return;remoteBusy=true;try{const{data,error}=await client.from('daily30_leaderboard_results').select('player_key,player_name,quiz_date,score,duration_seconds').gte('quiz_date',START).lte('quiz_date',today()).limit(10000);if(!error&&Array.isArray(data))REMOTE=data}catch(error){console.warn('Ljestvica nije osvježena:',error)}finally{remoteBusy=false;renderPreview();if(document.getElementById('leaderboard-page')?.classList.contains('open'))renderPage()}}
function injectVisibility(){const root=document.getElementById('leaderboard-preview');if(!root||document.getElementById('leaderboard-visibility-toggle'))return;const tabs=root.querySelector('.leaderboard-section-tabs');if(!tabs)return;const wrap=document.createElement('div');wrap.className='leaderboard-visibility';wrap.innerHTML=`<div class=\"leaderboard-visibility-copy\"><div class=\"leaderboard-visibility-title\">${lang()==='en'?'Show me on leaderboard':'Prikaži me na ljestvici'}</div><div class=\"leaderboard-visibility-note\">${lang()==='en'?'Your result stays saved when hidden.':'Rezultat ostaje spremljen i kad si skriven.'}</div></div><label class=\"leaderboard-switch\"><input id=\"leaderboard-visibility-toggle\" type=\"checkbox\"><span class=\"leaderboard-switch-track\"></span></label>`;tabs.insertAdjacentElement('beforebegin',wrap);const input=wrap.querySelector('input');input.checked=ownVisible();input.addEventListener('change',()=>{void window.KvizDaily30?.setLeaderboardVisibility?.(input.checked)})}
function injectFull(){if(document.getElementById('leaderboard-page'))return;"""
if old not in s: raise SystemExit('injectFull target not found')
s=s.replace(old,new,1)
old="""document.addEventListener('DOMContentLoaded',()=>{const root=document.getElementById('leaderboard-preview');if(root){previewState.view='daily30';previewState.anchor=currentAnchor('daily30');root.querySelectorAll('[data-leaderboard-view]').forEach(b=>b.addEventListener('click',()=>{previewState.view=b.dataset.leaderboardView;previewState.anchor=currentAnchor(previewState.view);root.dataset.expanded='0';document.getElementById('leaderboard-page')?.classList.remove('open');renderPreview()}));renderPreview()}renderAch();setInterval(()=>{refreshAll();updateAch()},1000);window.addEventListener('storage',e=>{if(String(e.key||'').startsWith('kviztogo_daily30_results_v1'))refreshAll()})});
window.KvizLeaderboards={refreshAll,renderPreview,renderPage,formatLeaderboardDuration:duration};"""
new="""document.addEventListener('DOMContentLoaded',()=>{const root=document.getElementById('leaderboard-preview');if(root){previewState.view='daily30';previewState.anchor=currentAnchor('daily30');root.querySelectorAll('[data-leaderboard-view]').forEach(b=>b.addEventListener('click',()=>{previewState.view=b.dataset.leaderboardView;previewState.anchor=currentAnchor(previewState.view);root.dataset.expanded='0';document.getElementById('leaderboard-page')?.classList.remove('open');renderPreview()}));injectVisibility();renderPreview();void reloadRemote()}renderAch();setInterval(()=>{refreshAll();updateAch()},1000);setInterval(()=>void reloadRemote(),15000);window.addEventListener('storage',e=>{if(String(e.key||'').startsWith('kviztogo_daily30_results_v1')||e.key==='kviztogo_daily30_leaderboard_visible_v1')refreshAll()})});
window.KvizLeaderboards={refreshAll,renderPreview,renderPage,reloadRemote,formatLeaderboardDuration:duration};"""
if old not in s: raise SystemExit('DOMContentLoaded target not found')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')
