from pathlib import Path
p=Path('daily30.js')
s=p.read_text(encoding='utf-8')
old='function setPlayerContext(identity){if(!identity||typeof identity!=="object")return;let guestId=null;try{const saved=JSON.parse(localStorage.getItem(GUEST_IDENTITY_KEY)||"null");guestId=saved?.id||null;}catch(_){}state.playerContext={isGuest:Boolean(identity.isGuest),userId:identity.userId||null,guestId:identity.isGuest?guestId:null,name:String(identity.isGuest?(getCustomGuestName()||""):(identity.name||"")).trim().slice(0,40)};try{localStorage.setItem(PLAYER_CONTEXT_KEY,JSON.stringify(state.playerContext));}catch(_){}if(!identity.isGuest&&identity.userId&&guestId){let client=null;try{client=typeof supabaseClient!=="undefined"?supabaseClient:null;}catch(_){}if(client){void client.rpc("daily30_attach_guest_to_current_user",{p_guest_player_key:`guest:${guestId}`}).then(({error,data})=>{if(!error&&data?.ok===true){if(data.results&&typeof data.results==="object")saveResults(data.results);renderCalendar();updateSelectionNote();window.KvizLeaderboards?.reloadRemote?.();window.KvizLeaderboards?.refreshAll?.();}}).catch(()=>{});}}}'
new='function setPlayerContext(identity){if(!identity||typeof identity!=="object")return;let guestId=null;try{const saved=JSON.parse(localStorage.getItem(GUEST_IDENTITY_KEY)||"null");guestId=saved?.id||null;}catch(_){}state.playerContext={isGuest:Boolean(identity.isGuest),userId:identity.userId||null,guestId:identity.isGuest?guestId:null,name:String(identity.isGuest?(getCustomGuestName()||""):(identity.name||"")).trim().slice(0,40)};try{localStorage.setItem(PLAYER_CONTEXT_KEY,JSON.stringify(state.playerContext));}catch(_){}if(!identity.isGuest&&identity.userId){void syncAuthenticatedDaily30(guestId);}}\n  async function syncAuthenticatedDaily30(guestId=null){let client=null;try{client=typeof supabaseClient!=="undefined"?supabaseClient:null;}catch(_){}if(!client)return false;try{if(guestId){const attached=await client.rpc("daily30_attach_guest_to_current_user",{p_guest_player_key:`guest:${guestId}`});if(attached.error)console.warn("Daily30 guest attach nije uspio:",attached.error);}const mine=await client.rpc("daily30_get_my_results");if(mine.error)throw mine.error;if(mine.data&&typeof mine.data==="object")saveResults(mine.data);renderCalendar();updateSelectionNote();window.KvizLeaderboards?.reloadRemote?.();window.KvizLeaderboards?.refreshAll?.();return true;}catch(error){console.warn("Daily30 profilni rezultati nisu sinkronizirani:",error);return false;}}\n  async function syncDaily30AuthSession(session){const user=session?.user||null;if(!user){state.playerContext=null;try{localStorage.removeItem(PLAYER_CONTEXT_KEY);}catch(_){}return false;}let name=user.user_metadata?.username||user.user_metadata?.full_name||user.user_metadata?.name||user.email?.split("@")[0]||"Kvizoman";let client=null;try{client=typeof supabaseClient!=="undefined"?supabaseClient:null;}catch(_){}if(client){try{const q=await client.from("profiles").select("username").eq("id",user.id).maybeSingle();if(q.data?.username)name=q.data.username;}catch(_){}}setPlayerContext({isGuest:false,userId:user.id,name});return true;}'
if s.count(old)!=1: raise SystemExit(f'setPlayerContext target count {s.count(old)}')
s=s.replace(old,new,1)
old2='async function initOnline(){state.selectedDate=zonedDateKey();state.calendarMonth=`${state.selectedDate.slice(0,7)}-01`;await loadIndex();document.getElementById("daily30-current-choice")?.addEventListener("click",selectToday);'
new2='async function initOnline(){state.selectedDate=zonedDateKey();state.calendarMonth=`${state.selectedDate.slice(0,7)}-01`;await loadIndex();try{if(typeof supabaseClient!=="undefined"&&supabaseClient){const sessionResult=await supabaseClient.auth.getSession();await syncDaily30AuthSession(sessionResult.data?.session||null);supabaseClient.auth.onAuthStateChange((_event,session)=>{void syncDaily30AuthSession(session);});}}catch(error){console.warn("Daily30 auth sinkronizacija nije pokrenuta:",error);}document.getElementById("daily30-current-choice")?.addEventListener("click",selectToday);'
if s.count(old2)!=1: raise SystemExit(f'initOnline target count {s.count(old2)}')
s=s.replace(old2,new2,1)
p.write_text(s,encoding='utf-8')
